# Generated by Django 4.1.5 on 2023-01-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoffice', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='remaining_overridden',
            field=models.BooleanField(help_text="This field indicates whether or not the Task's remaining field has been overridden by a user.", null=True),
        ),
    ]
