# Generated by Django 4.1.5 on 2023-01-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoffice', '0003_alter_task_remaining_overridden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='remaining_overridden',
            field=models.BooleanField(default=False, help_text="This field indicates whether or not the Task's remaining field has been overridden by a user."),
        ),
    ]
