# Generated by Django 4.1.5 on 2023-01-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoffice', '0004_alter_activity_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='billing_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_contact_jobs', to='djangoffice.contact'),
        ),
        migrations.AlterField(
            model_name='job',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_contact_jobs', to='djangoffice.contact'),
        ),
    ]
